grimblast: make sure that the virtual display is not included in a screenshot

diff --git a/grimblast/grimblast b/grimblast/grimblast
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -197,7 +197,7 @@ takeScreenshot() {
   if [ -n "$OUTPUT" ]; then
    moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
   elif [ -z "$GEOM" ]; then
-   moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
+   grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
    moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
     resetFade
