grimblast: add '' around variables.

diff --git a/grimblast/grimblast b/grimblast/grimblast
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -180,14 +180,14 @@ moveCursorPosition() {
   virtualDisplayName="grimblastVD"
   focusedMonitorName=$(hyprctl -j monitors | jq -r '.[] | select( .focused == true ) | .name')
 
-  hyprctl output create headless $virtualDisplayName >/dev/null
-  hyprctl dispatch focusmonitor $virtualDisplayName >/dev/null
+  hyprctl output create headless "$virtualDisplayName" >/dev/null
+  hyprctl dispatch focusmonitor "$virtualDisplayName" >/dev/null
 }
 
 restoreCursorPosition() {
-  hyprctl dispatch focusmonitor $focusedMonitorName >/dev/null
-  hyprctl output remove $virtualDisplayName >/dev/null
-  hyprctl dispatch movecursor ${initialCursorPosition//,} >/dev/null
+  hyprctl dispatch focusmonitor "$focusedMonitorName" >/dev/null
+  hyprctl output remove "$virtualDisplayName" >/dev/null
+  hyprctl dispatch movecursor "${initialCursorPosition//,}" >/dev/null
 }
 
 takeScreenshot() {
@@ -195,11 +195,11 @@ takeScreenshot() {
   GEOM=$2
   OUTPUT=$3
   if [ -n "$OUTPUT" ]; then
-   moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
+    moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
   elif [ -z "$GEOM" ]; then
-   grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
+    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
-   moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
+    moveCursorPosition && grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" && restoreCursorPosition || die "Unable to invoke grim"
     resetFade
   fi
 }
