grimblast: update man pages

diff --git a/grimblast/grimblast b/grimblast/grimblast
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -70,6 +70,15 @@ while [[ $# -gt 0 ]]; do
     OPENFILE_NOTIFICATION=yes
     shift
     ;;
+  -e | --expire-time)
+    if [[ -n "${2-}" && "$2" =~ ^[0-9]+$ ]]; then
+      EXPIRE_TIME=$2
+      shift 2
+    else
+      echo "Invalid or missing argument for --expire-time" >&2
+      exit 1
+    fi
+    ;;
   -c | --cursor)
     CURSOR=yes
     shift
@@ -93,15 +102,6 @@ while [[ $# -gt 0 ]]; do
       shift 2
     else
       echo "Invalid or missing argument for --scale" >&2
-      exit 1
-    fi
-    ;;
-  -e | --expire-time)
-    if [[ -n "${2-}" && "$2" =~ ^[0-9]+$ ]]; then
-      EXPIRE_TIME=$2
-      shift 2
-    else
-      echo "Invalid or missing argument for --expire-time" >&2
       exit 1
     fi
     ;;
@@ -135,7 +135,7 @@ FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date -Ins).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--openfile] [--cursor] [--freeze] [--wait N] [--scale <scale>] [--expire-time <ms>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--openfile] [--expire-time <ms>] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
