grimblast: fix stdout output for copysave

diff --git a/grimblast/grimblast b/grimblast/grimblast
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -317,9 +317,14 @@ elif [ "$ACTION" = "edit" ]; then
   fi
 else
   if [ "$ACTION" = "copysave" ]; then
-    takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
-    notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
-    echo "$FILE"
+    if [ "$FILE" = "-" ]; then
+        takeScreenshot - "$GEOM" "$OUTPUT" | tee >(wl-copy --type image/png) || die "Clipboard error"
+        notifyOk "$WHAT copied to buffer and piped to stdout"
+    else
+        takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
+        notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
+        echo "$FILE"
+    fi
   else
     notifyError "Error taking screenshot with grim"
   fi
