grimblast: add notification expire-time flag (#173)

diff --git a/grimblast/grimblast b/grimblast/grimblast
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -55,6 +55,7 @@ CURSOR=
 FREEZE=
 WAIT=no
 SCALE=
+EXPIRE_TIME=3000
 
 # Store positional arguments
 pos=()
@@ -68,6 +69,15 @@ while [[ $# -gt 0 ]]; do
   -o | --openfile)
     OPENFILE_NOTIFICATION=yes
     shift
+    ;;
+  -e | --expire-time)
+    if [[ -n "${2-}" && "$2" =~ ^[0-9]+$ ]]; then
+      EXPIRE_TIME=$2
+      shift 2
+    else
+      echo "Invalid or missing argument for --expire-time" >&2
+      exit 1
+    fi
     ;;
   -c | --cursor)
     CURSOR=yes
@@ -125,7 +135,7 @@ FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date -Ins).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--openfile] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--openfile] [--expire-time <ms>] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
@@ -146,7 +156,7 @@ if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ]
 fi
 
 notify() {
-  notify-send -t 3000 -a grimblast "$@"
+  notify-send -t "$EXPIRE_TIME" -a grimblast "$@"
 }
 
 notifyOk() {
